In [1]:
import os
os.getcwd()

'C:\\Users\\Abhishek Kamale'

In [44]:
import numpy as np
no = np.arange(10)

In [27]:
no


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
m = np.matrix('1,2,3;4,5,6')

In [36]:
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [37]:
np.transpose(m)

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [41]:
m * 5
m / 2

matrix([[0.5, 1. , 1.5],
        [2. , 2.5, 3. ]])

In [33]:
import pandas as pd
df = pd.DataFrame({'Emp_id':[1,2,3,4,5],
                  'Name':['Ishwar','Akash','Aunp','Nikhil','Shubham'],
                  'Gender':['M','M','M','F','M']})

In [ ]:
from ggplot import mtcars
df_mtcars = mtcars