In [5]:
import os
os.getcwd()


'C:\\Users\\ishwar.suresh.borse'

In [4]:
import numpy as np
no = np.arange(10)

In [27]:
no


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
m = np.matrix('1,2,3;4,5,6')

In [17]:
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [18]:
np.transpose(m)

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [41]:
m * 5
m / 2

matrix([[0.5, 1. , 1.5],
        [2. , 2.5, 3. ]])

In [38]:
import pandas as pd
df = pd.DataFrame({'Emp_id':[1,2,3,4,5],
                  'Name':['Ishwar','Akash','Aunp','Nikhil','Shubham'],
                  'Gender':['M','M','M','F','M']})

In [8]:
from ggplot import mtcars
df_mtcars = mtcars

In [27]:
df_mtcars

name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [12]:
df_mtcars_sub = df_mtcars[['cyl','carb','hp']]

KeyError: ('cyl', 'carb', 'hp')

In [11]:
df_mtcars_sub

cyl  carb   hp
0     6     4  110
1     6     4  110
2     4     1   93
3     6     1  110
4     8     2  175
5     6     1  105
6     8     4  245
7     4     2   62
8     4     2   95
9     6     4  123
10    6     4  123
11    8     3  180
12    8     3  180
13    8     3  180
14    8     4  205
15    8     4  215
16    8     4  230
17    4     1   66
18    4     2   52
19    4     1   65
20    4     1   97
21    8     2  150
22    8     2  150
23    8     4  245
24    8     2  175
25    4     1   66
26    4     2   91
27    4     2  113
28    8     4  264
29    6     6  175
30    8     8  335
31    4     2  109

In [31]:
df_mtcars_cond = df_mtcars_sub.loc[(df_mtcars['cyl']==4) | (df_mtcars['carb']==4)]

In [32]:
df_mtcars_cond

cyl  carb   hp
0     6     4  110
1     6     4  110
2     4     1   93
6     8     4  245
7     4     2   62
8     4     2   95
9     6     4  123
10    6     4  123
14    8     4  205
15    8     4  215
16    8     4  230
17    4     1   66
18    4     2   52
19    4     1   65
20    4     1   97
23    8     4  245
25    4     1   66
26    4     2   91
27    4     2  113
28    8     4  264
31    4     2  109

In [33]:
df_mtcars['New_var'] = np.log(df_mtcars['cyl'])

In [34]:
df_mtcars

name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb   New_var  
0      4     4  1.791759  
1      4     4  1.791759  
2      4     1  1.386294  
3      3     1  1.791759  
4      3     2  2.079442  
5      3     1  1.791759  
6      3     4  2.079442  
7      4     2  1.386294  
8      4     2  1.386294  
9      4     4  1.791759  
10     4     4  1.791759  
11     3     3  2.079442  
12     3     3  2.079442  
13     3     3  2.079442  
14     3     4  2.079442  
15     3     4  2.079442  
16     3     4  2.079442  
17     4     1  1.386294  
18     4     2  1.386294  
19     4     1  1.386294  
20     3     1  1.386294  
21     3     2  2.079442  
22     3     2  2.079442  
23     3     4  2.079442  
24     3     2  2.079442  
25     4     1  1.386294  
26     5     2  1.386294  
27     5     2  1.386294  
28     5     4  2.079442  
29     5     6  1.791759  
30     5     8  2.079442  
31     4     2  1.386294

In [40]:
df1 = pd.DataFrame({'a':[1,2,3,4],'b':[5,6,7,8]})
df2 = pd.DataFrame({'a':[11,2,33,4],'b':[55,6,77,8]})

In [41]:
df1


a  b
0  1  5
1  2  6
2  3  7
3  4  8

In [42]:
df2

a   b
0  11  55
1   2   6
2  33  77
3   4   8

In [43]:
df3 = df1.append(df2)

In [45]:
df3

a   b
0   1   5
1   2   6
2   3   7
3   4   8
0  11  55
1   2   6
2  33  77
3   4   8

In [63]:
df4 = pd.concat([df1.reset_index(drop = True ),df2],axis =1)

In [64]:
df4

a  b   a   b
0  1  5  11  55
1  2  6   2   6
2  3  7  33  77
3  4  8   4   8

In [89]:
df_mtcars['cyl'] = df_mtcars['cyl'].astype(object)

In [90]:
type(df_mtcars['cyl'])

pandas.core.series.Series

In [91]:
df_mtcars['cyl']

0     6
1     6
2     4
3     6
4     8
5     6
6     8
7     4
8     4
9     6
10    6
11    8
12    8
13    8
14    8
15    8
16    8
17    4
18    4
19    4
20    4
21    8
22    8
23    8
24    8
25    4
26    4
27    4
28    8
29    6
30    8
31    4
Name: cyl, dtype: object

In [92]:
df_mtcars = df_mtcars.astype(object)

In [95]:
df_mtcars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 13 columns):
name       32 non-null object
mpg        32 non-null object
cyl        32 non-null object
disp       32 non-null object
hp         32 non-null object
drat       32 non-null object
wt         32 non-null object
qsec       32 non-null object
vs         32 non-null object
am         32 non-null object
gear       32 non-null object
carb       32 non-null object
New_var    32 non-null object
dtypes: object(13)
memory usage: 3.3+ KB


In [98]:
df_mtcars['mpgcat'] = np.where(df_mtcars['mpg']>20 ,'Low',0)

In [99]:
df_mtcars

name   mpg cyl   disp   hp  drat     wt   qsec vs am gear  \
0             Mazda RX4    21   6    160  110   3.9   2.62  16.46  0  1    4   
1         Mazda RX4 Wag    21   6    160  110   3.9  2.875  17.02  0  1    4   
2            Datsun 710  22.8   4    108   93  3.85   2.32  18.61  1  1    4   
3        Hornet 4 Drive  21.4   6    258  110  3.08  3.215  19.44  1  0    3   
4     Hornet Sportabout  18.7   8    360  175  3.15   3.44  17.02  0  0    3   
5               Valiant  18.1   6    225  105  2.76   3.46  20.22  1  0    3   
6            Duster 360  14.3   8    360  245  3.21   3.57  15.84  0  0    3   
7             Merc 240D  24.4   4  146.7   62  3.69   3.19     20  1  0    4   
8              Merc 230  22.8   4  140.8   95  3.92   3.15   22.9  1  0    4   
9              Merc 280  19.2   6  167.6  123  3.92   3.44   18.3  1  0    4   
10            Merc 280C  17.8   6  167.6  123  3.92   3.44   18.9  1  0    4   
11           Merc 450SE  16.4   8  275.8  180  3.07   4.07   17.4  0  0    3   
12           Merc 450SL  17.3   8  275.8  180  3.07   3.73   17.6  0  0    3   
13          Merc 450SLC  15.2   8  275.8  180  3.07   3.78     18  0  0    3   
14   Cadillac Fleetwood  10.4   8    472  205  2.93   5.25  17.98  0  0    3   
15  Lincoln Continental  10.4   8    460  215     3  5.424  17.82  0  0    3   
16    Chrysler Imperial  14.7   8    440  230  3.23  5.345  17.42  0  0    3   
17             Fiat 128  32.4   4   78.7   66  4.08    2.2  19.47  1  1    4   
18          Honda Civic  30.4   4   75.7   52  4.93  1.615  18.52  1  1    4   
19       Toyota Corolla  33.9   4   71.1   65  4.22  1.835   19.9  1  1    4   
20        Toyota Corona  21.5   4  120.1   97   3.7  2.465  20.01  1  0    3   
21     Dodge Challenger  15.5   8    318  150  2.76   3.52  16.87  0  0    3   
22          AMC Javelin  15.2   8    304  150  3.15  3.435   17.3  0  0    3   
23           Camaro Z28  13.3   8    350  245  3.73   3.84  15.41  0  0    3   
24     Pontiac Firebird  19.2   8    400  175  3.08  3.845  17.05  0  0    3   
25            Fiat X1-9  27.3   4     79   66  4.08  1.935   18.9  1  1    4   
26        Porsche 914-2    26   4  120.3   91  4.43   2.14   16.7  0  1    5   
27         Lotus Europa  30.4   4   95.1  113  3.77  1.513   16.9  1  1    5   
28       Ford Pantera L  15.8   8    351  264  4.22   3.17   14.5  0  1    5   
29         Ferrari Dino  19.7   6    145  175  3.62   2.77   15.5  0  1    5   
30        Maserati Bora    15   8    301  335  3.54   3.57   14.6  0  1    5   
31           Volvo 142E  21.4   4    121  109  4.11   2.78   18.6  1  1    4   

   carb  New_var mpgcat  
0     4  1.79176    Low  
1     4  1.79176    Low  
2     1  1.38629    Low  
3     1  1.79176    Low  
4     2  2.07944      0  
5     1  1.79176      0  
6     4  2.07944      0  
7     2  1.38629    Low  
8     2  1.38629    Low  
9     4  1.79176      0  
10    4  1.79176      0  
11    3  2.07944      0  
12    3  2.07944      0  
13    3  2.07944      0  
14    4  2.07944      0  
15    4  2.07944      0  
16    4  2.07944      0  
17    1  1.38629    Low  
18    2  1.38629    Low  
19    1  1.38629    Low  
20    1  1.38629    Low  
21    2  2.07944      0  
22    2  2.07944      0  
23    4  2.07944      0  
24    2  2.07944      0  
25    1  1.38629    Low  
26    2  1.38629    Low  
27    2  1.38629    Low  
28    4  2.07944      0  
29    6  1.79176      0  
30    8  2.07944      0  
31    2  1.38629    Low

In [104]:
df_mtcars = df_mtcars.sort_values('mpg', ascending=True)

In [105]:
df_mtcars

name   mpg cyl   disp   hp  drat     wt   qsec vs am gear  \
15  Lincoln Continental  10.4   8    460  215     3  5.424  17.82  0  0    3   
14   Cadillac Fleetwood  10.4   8    472  205  2.93   5.25  17.98  0  0    3   
23           Camaro Z28  13.3   8    350  245  3.73   3.84  15.41  0  0    3   
6            Duster 360  14.3   8    360  245  3.21   3.57  15.84  0  0    3   
16    Chrysler Imperial  14.7   8    440  230  3.23  5.345  17.42  0  0    3   
30        Maserati Bora    15   8    301  335  3.54   3.57   14.6  0  1    5   
13          Merc 450SLC  15.2   8  275.8  180  3.07   3.78     18  0  0    3   
22          AMC Javelin  15.2   8    304  150  3.15  3.435   17.3  0  0    3   
21     Dodge Challenger  15.5   8    318  150  2.76   3.52  16.87  0  0    3   
28       Ford Pantera L  15.8   8    351  264  4.22   3.17   14.5  0  1    5   
11           Merc 450SE  16.4   8  275.8  180  3.07   4.07   17.4  0  0    3   
12           Merc 450SL  17.3   8  275.8  180  3.07   3.73   17.6  0  0    3   
10            Merc 280C  17.8   6  167.6  123  3.92   3.44   18.9  1  0    4   
5               Valiant  18.1   6    225  105  2.76   3.46  20.22  1  0    3   
4     Hornet Sportabout  18.7   8    360  175  3.15   3.44  17.02  0  0    3   
24     Pontiac Firebird  19.2   8    400  175  3.08  3.845  17.05  0  0    3   
9              Merc 280  19.2   6  167.6  123  3.92   3.44   18.3  1  0    4   
29         Ferrari Dino  19.7   6    145  175  3.62   2.77   15.5  0  1    5   
0             Mazda RX4    21   6    160  110   3.9   2.62  16.46  0  1    4   
1         Mazda RX4 Wag    21   6    160  110   3.9  2.875  17.02  0  1    4   
3        Hornet 4 Drive  21.4   6    258  110  3.08  3.215  19.44  1  0    3   
31           Volvo 142E  21.4   4    121  109  4.11   2.78   18.6  1  1    4   
20        Toyota Corona  21.5   4  120.1   97   3.7  2.465  20.01  1  0    3   
8              Merc 230  22.8   4  140.8   95  3.92   3.15   22.9  1  0    4   
2            Datsun 710  22.8   4    108   93  3.85   2.32  18.61  1  1    4   
7             Merc 240D  24.4   4  146.7   62  3.69   3.19     20  1  0    4   
26        Porsche 914-2    26   4  120.3   91  4.43   2.14   16.7  0  1    5   
25            Fiat X1-9  27.3   4     79   66  4.08  1.935   18.9  1  1    4   
27         Lotus Europa  30.4   4   95.1  113  3.77  1.513   16.9  1  1    5   
18          Honda Civic  30.4   4   75.7   52  4.93  1.615  18.52  1  1    4   
17             Fiat 128  32.4   4   78.7   66  4.08    2.2  19.47  1  1    4   
19       Toyota Corolla  33.9   4   71.1   65  4.22  1.835   19.9  1  1    4   

   carb  New_var mpgcat  
15    4  2.07944      0  
14    4  2.07944      0  
23    4  2.07944      0  
6     4  2.07944      0  
16    4  2.07944      0  
30    8  2.07944      0  
13    3  2.07944      0  
22    2  2.07944      0  
21    2  2.07944      0  
28    4  2.07944      0  
11    3  2.07944      0  
12    3  2.07944      0  
10    4  1.79176      0  
5     1  1.79176      0  
4     2  2.07944      0  
24    2  2.07944      0  
9     4  1.79176      0  
29    6  1.79176      0  
0     4  1.79176    Low  
1     4  1.79176    Low  
3     1  1.79176    Low  
31    2  1.38629    Low  
20    1  1.38629    Low  
8     2  1.38629    Low  
2     1  1.38629    Low  
7     2  1.38629    Low  
26    2  1.38629    Low  
25    1  1.38629    Low  
27    2  1.38629    Low  
18    2  1.38629    Low  
17    1  1.38629    Low  
19    1  1.38629    Low

In [106]:
del df1

In [107]:
del df2

In [112]:
df1 = pd.DataFrame({'A':range(1,6),
                    'B':np.random.randint(5,105,size=5),
                    'C':['Toaster','Toaster','Ohio','Toaster','Ohio']})
df2 = pd.DataFrame({'A':[2,4,5],
                    'B':['Medium','Classic','Deluxe']})

In [113]:
df1

A   B        C
0  1  34  Toaster
1  2  88  Toaster
2  3  64     Ohio
3  4  39  Toaster
4  5  23     Ohio

In [114]:
df2

A        B
0  2   Medium
1  4  Classic
2  5   Deluxe

In [120]:
df_left = df1.merge(df2,on = 'A',how='left')

In [121]:
df_left

A  B_x        C      B_y
0  1   34  Toaster      NaN
1  2   88  Toaster   Medium
2  3   64     Ohio      NaN
3  4   39  Toaster  Classic
4  5   23     Ohio   Deluxe

In [122]:
df_right = df1.merge(df2,on = 'A',how='right')

In [123]:
df_right

A  B_x        C      B_y
0  2   88  Toaster   Medium
1  4   39  Toaster  Classic
2  5   23     Ohio   Deluxe